# This workflow integrates Qwiet preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet Scan

on:
  workflow_dispatch:
jobs:
  build-scan:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Downloading the Qwiet CLI and set permissions
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Setup Scala
      uses: olafurpg/setup-scala@v14
      with:
        scala-version: 2.12.4 # Replace with your desired Scala version

    - name: SBT Build
      run: |
        sbt stage

    - name: Find JAR
      run: |
        find . -type f | grep -E 'war|jar'
        
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --app SEC-vuln-test --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}  --java $(pwd)/target/helloshiftleft-scala-0.0.1-SNAPSHOT.jar
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
